# Generated by Django 3.1.7 on 2021-02-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0015_delete_poshuseradmin'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_useradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
