# Generated by Django 3.1.7 on 2021-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts_to_maintain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email_password',
            field=models.CharField(default='', max_length=50, verbose_name='Email Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='master_email',
            field=models.EmailField(default='', help_text='Where all the emails for your accounts will forward to', max_length=254, verbose_name='Master Email'),
        ),
    ]
