# Generated by Django 3.1.6 on 2021-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoshUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_signed_up', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('', 'In Use'), ('', 'Active'), ('', 'Inactive')], max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('', ''), ('2', 'Male'), ('1', 'Female'), ('0', 'Unspecified')], max_length=20)),
            ],
        ),
    ]
