# Generated by Django 3.1.6 on 2021-02-18 19:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
