# Generated by Django 3.1.6 on 2021-02-18 23:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0002_poshuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='email',
            field=models.EmailField(help_text='Email in which the account will be signed up with on Posh Mark', max_length=254),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile_pictures'),
        ),
    ]
