# Generated by Django 3.1.6 on 2021-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0004_auto_20210218_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='alias_email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='masked_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('0', 'In Use'), ('1', 'Active'), ('2', 'Inactive'), ('3', 'Waiting for alias email to be verified.')], max_length=20),
        ),
    ]
