# Generated by Django 3.1.6 on 2021-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0005_auto_20210219_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='alias_email_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='masked_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('0', 'In Use'), ('1', 'Active'), ('2', 'Inactive'), ('3', 'Waiting for alias email to be verified'), ('4', 'Waiting to be registered'), ('5', 'Registering')], max_length=20),
        ),
    ]
