# Generated by Django 3.1.7 on 2021-02-21 21:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0006_auto_20210219_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='header_picture',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='header_pictures'),
            preserve_default=False,
        ),
    ]
