# Generated by Django 3.1.7 on 2021-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0008_auto_20210222_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
