# Generated by Django 3.1.7 on 2021-02-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0009_auto_20210222_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='password',
            field=models.CharField(help_text='Must be at least 6 characters and must contain a number or symbol.', max_length=20),
        ),
    ]
