# Generated by Django 3.1.7 on 2021-02-22 04:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0010_auto_20210222_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='header_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
