# Generated by Django 3.1.7 on 2021-02-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0011_auto_20210222_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poshuser',
            old_name='is_signed_up',
            new_name='is_registered',
        ),
    ]
