# Generated by Django 3.1.7 on 2021-02-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0013_poshuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoshUserAdmin',
            fields=[
                ('poshuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poshmark.poshuser')),
            ],
            bases=('poshmark.poshuser',),
        ),
    ]
