# Generated by Django 3.1.7 on 2021-02-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0014_poshuseradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoshUserAdmin',
        ),
    ]
