# Generated by Django 3.1.7 on 2021-02-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0015_delete_poshuseradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='is_active',
        ),
    ]
