# Generated by Django 3.1.7 on 2021-02-24 19:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0016_remove_poshuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='email',
            field=models.EmailField(blank=True, help_text='If alias is chosen up top then put the email you wish to mask here. Otherwise put the email you wish to create the Posh User with.', max_length=254),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('2', 'Male'), ('1', 'Female'), ('0', 'Unspecified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='header_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=''),
        ),
    ]
