# Generated by Django 3.1.7 on 2021-03-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0017_auto_20210224_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_type', models.CharField(choices=[('0', 'Other'), ('1', 'Registration'), ('2', 'Campaign')], max_length=10)),
                ('created', models.DateTimeField(editable=False)),
                ('posh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshmark.poshuser')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshmark.log')),
            ],
        ),
    ]
