# Generated by Django 3.1.7 on 2021-03-08 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poshmark', '0018_log_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('tags', models.BooleanField(default=False)),
                ('original_price', models.IntegerField()),
                ('listing_price', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshmark.listing')),
            ],
        ),
    ]
