# Generated by Django 3.1.7 on 2021-03-10 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poshmark', '0019_listing_listingphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('1', 'Running'), ('2', 'Idle')], max_length=15)),
                ('times', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('delay', models.IntegerField()),
                ('auto_run', models.BooleanField(default=False)),
                ('generate_users', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(to='poshmark.Listing')),
                ('posh_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poshmark.poshuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
