# Generated by Django 3.1.7 on 2021-03-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0020_auto_20210311_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='listings',
        ),
        migrations.AddField(
            model_name='campaign',
            name='mode',
            field=models.CharField(choices=[('0', 'Basic Sharing'), ('0', 'Basic Sharing')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poshmark.campaign'),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('0', 'In Use'), ('1', 'Active'), ('2', 'Inactive'), ('3', 'Waiting for alias email to be verified'), ('4', 'Waiting to be registered'), ('4', 'Registering'), ('6', 'Updating Profile')], max_length=20),
        ),
    ]
