# Generated by Django 3.1.7 on 2021-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0021_auto_20210314_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='mode',
            field=models.CharField(choices=[('0', 'Basic Sharing'), ('1', 'Advanced Sharing')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'Running'), ('2', 'Idle'), ('3', 'Stopping')], max_length=15),
        ),
    ]
