# Generated by Django 3.1.7 on 2021-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0022_auto_20210315_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='error_during_listing',
        ),
        migrations.AddField(
            model_name='poshuser',
            name='proxy_port',
            field=models.IntegerField(null=True),
        ),
    ]
