# Generated by Django 3.1.7 on 2021-04-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0026_auto_20210401_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='posh_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poshmark.poshuser'),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='proxy_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
