# Generated by Django 3.1.7 on 2021-04-07 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poshmark', '0027_auto_20210406_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='proxy_port',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='posh_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poshmark.poshuser'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
