# Generated by Django 3.1.7 on 2021-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0028_auto_20210407_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('0', 'In Use'), ('1', 'Active'), ('2', 'Inactive'), ('3', 'Waiting for alias email to be verified'), ('4', 'Registering'), ('5', 'Updating Profile')], max_length=20),
        ),
    ]
