# Generated by Django 3.1.7 on 2021-05-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0029_auto_20210502_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
