# Generated by Django 3.1.7 on 2021-05-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0030_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
