# Generated by Django 3.1.7 on 2021-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0031_poshuser_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoshProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=False)),
                ('max_accounts', models.IntegerField()),
                ('registered_accounts', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
    ]
