# Generated by Django 3.1.7 on 2021-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0032_poshproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshproxy',
            name='ip_reset_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
