# Generated by Django 3.1.7 on 2021-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0033_poshproxy_ip_reset_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshproxy',
            name='in_use',
        ),
        migrations.AddField(
            model_name='poshproxy',
            name='current_connections',
            field=models.IntegerField(default=0),
        ),
    ]
