# Generated by Django 3.1.7 on 2021-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0034_auto_20210519_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'Running'), ('2', 'Idle'), ('3', 'Stopping'), ('4', 'Starting')], max_length=15),
        ),
    ]
