# Generated by Django 3.1.7 on 2021-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0035_auto_20210519_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshproxy',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
