# Generated by Django 3.1.7 on 2021-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0038_auto_20210521_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'Running'), ('2', 'Idle'), ('3', 'Stopping'), ('4', 'Starting'), ('5', 'Restarting')], max_length=15),
        ),
    ]
