# Generated by Django 3.1.7 on 2021-06-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0040_listing_lowest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lowest_price',
            field=models.IntegerField(blank=True, default=250),
        ),
    ]
