# Generated by Django 3.1.7 on 2021-06-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0042_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshproxy',
            name='current_connections',
        ),
        migrations.AddField(
            model_name='poshproxy',
            name='max_connections',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ProxyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('posh_proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshmark.poshproxy')),
                ('posh_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poshmark.poshuser')),
            ],
        ),
    ]
