# Generated by Django 3.1.7 on 2021-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0043_auto_20210611_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='meet_posh',
        ),
        migrations.AddField(
            model_name='poshuser',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('0', 'In Use'), ('2', 'Inactive'), ('3', 'Campaign running'), ('4', 'Registering')], max_length=20),
        ),
    ]
