# Generated by Django 3.1.7 on 2021-06-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0045_auto_20210612_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='posh_user',
        ),
        migrations.AddField(
            model_name='log',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poshmark.campaign'),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('1', 'Idle'), ('2', 'Inactive'), ('3', 'Campaign running'), ('4', 'Registering')], max_length=20),
        ),
    ]
