# Generated by Django 3.1.7 on 2021-06-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0046_auto_20210613_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='created',
            new_name='created_date',
        ),
    ]
