# Generated by Django 3.1.7 on 2021-06-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0047_auto_20210613_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logger_type',
        ),
    ]
