# Generated by Django 3.1.7 on 2021-06-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0048_remove_log_logger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='posh_user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
