# Generated by Django 3.1.7 on 2021-06-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0049_log_posh_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='port',
        ),
    ]
