# Generated by Django 3.1.7 on 2021-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0050_remove_poshuser_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='redis_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='redis_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='poshproxy',
            name='redis_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='redis_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
