# Generated by Django 3.1.7 on 2021-07-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0051_auto_20210706_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshproxy',
            name='registration_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poshproxy',
            name='max_accounts',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='poshproxy',
            name='redis_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='poshproxy',
            name='registered_accounts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
