# Generated by Django 3.1.7 on 2021-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0055_auto_20210710_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='alias_email_id',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='masked_email',
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='header_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='status',
            field=models.CharField(choices=[('1', 'Idle'), ('2', 'Inactive'), ('3', 'Campaign running'), ('4', 'Registering'), ('5', 'Email Creation')], max_length=20),
        ),
    ]
