# Generated by Django 3.1.7 on 2021-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0056_auto_20210724_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='dob_day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='dob_month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='dob_year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
