# Generated by Django 3.1.7 on 2021-07-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0058_auto_20210724_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mode',
            field=models.CharField(choices=[('0', 'Basic Sharing'), ('1', 'Advanced Sharing'), ('2', 'Register')], default='0', max_length=10),
        ),
    ]
