# Generated by Django 3.1.7 on 2021-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0063_auto_20210725_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
