# Generated by Django 3.1.7 on 2021-08-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0066_poshuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='profile_picture_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
