# Generated by Django 3.1.7 on 2021-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0067_poshuser_profile_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mode',
            field=models.CharField(choices=[('0', 'Basic Sharing'), ('1', 'Advanced Sharing'), ('2', 'Register'), ('3', 'List Item'), ('4', 'Aging')], default='0', max_length=10),
        ),
    ]
