# Generated by Django 3.1.7 on 2021-08-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0068_auto_20210827_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poshproxy',
            old_name='registration_proxy',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='email_forwarding_enabled',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='email_less_secure_apps_allowed',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='email_registered',
        ),
        migrations.AddField(
            model_name='poshuser',
            name='email_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
