# Generated by Django 3.1.7 on 2021-08-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshmark', '0069_auto_20210828_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='email_id',
            field=models.CharField(default='', max_length=150),
        ),
    ]
