version: '3.7'

services:
  poshbot:
    image: ghcr.io/mredwin1/poshbot:latest
    build:
      context: .
      dockerfile: PoshBot.Dockerfile
    container_name: poshbot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery_concurrency
      - celery_beat
      - celery_noconcurrency
    networks:
      - traefik
      - internal
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.dms.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"
      # Allow request only from the predefined entry point named "websecure"
      - "traefik.http.routers.dms.entrypoints=websecure"
      # Tell it to listen to port 80 inside the Docker container
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # Traefik will use the traefik_default docker network
      - "traefik.docker.network=traefik_default"
      # Automatic Certificate Generation
      - "traefik.http.routers.dms.tls=true"
      - "traefik.http.routers.dms.tls.certresolver=le"

    # Bind volumes to enable hot-reloads.
    # e.g. when a file is changed in this folder, the change is
    # also applied to the same file inside the docker container.
    volumes:
      - ./PoshBot/:/PoshBot/
      - ./poshmark/:/poshmark/
#      - ./media/:/shared_volume/media
      - /dev/shm:/dev/shm
      - shared_volume:/shared_volume
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: postgres_poshbot
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    networks:
      - internal
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    container_name: redis_poshbot
    networks:
      - internal
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    networks:
      - traefik
    command:
      - "--log.level=${TRAEFIK_LOG}"
      - "--api.insecure=false"
      - "--providers.docker=true"
      # All docker containers must be _explicitely_ exposed with traefik.enable=true
      - "--providers.docker.exposedbydefault=false"
      # Traefik will listen to _incoming requests_ on port 80 and 443
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # SSL Set Up
      - "--certificatesResolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/letsencrypt/acme.json:/acme.json"
  celery_concurrency:
    image: ghcr.io/mredwin1/poshbot:latest
    container_name: celery_concurrency_poshbot
    restart: always
    entrypoint: celery -A PoshBot worker --concurrency=100 -Q concurrency -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./PoshBot/:/PoshBot/
      - ./poshmark/:/poshmark/
      - shared_volume:/shared_volume
      - /dev/shm:/dev/shm
      - ./poshmark/static/poshmark/images:/static/poshmark/images
  celery_noconcurrency:
    image: ghcr.io/mredwin1/poshbot:latest
    container_name: celery_noconcurrency_poshbot
    restart: always
    entrypoint: celery -A PoshBot worker --concurrency=1 -Q no_concurrency -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./PoshBot/:/PoshBot/
      - ./poshmark/:/poshmark/
      - /dev/shm:/dev/shm
  celery_beat:
    image: ghcr.io/mredwin1/poshbot:latest
    container_name: celery_beat_poshbot
    restart: always
    entrypoint: celery -A PoshBot beat -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - shared_volume:/shared_volume
      - /dev/shm:/dev/shm

networks:
  internal:
  traefik:
    external:
      name: traefik_default

volumes:
  postgres_db:
  shared_volume:
  lpm_data:
